"""
Targeted supplement training data for two diagnosed failure modes.

B4 (mixed-context instantiation):
  Root cause: model trained on 2-premise oracle sets; refuses on 4-premise input
  even when the 2 supporting premises are present among the 4.
  Fix: examples where the correct 2-premise support is embedded in a larger
  retrieved set containing 2 unrelated noise premises.

B3 (disjunctive syllogism wrong direction):
  Root cause: model negates the GOAL-SIDE disjunct ("software bug did NOT cause")
  instead of the EVIDENCE-SIDE disjunct ("hardware did NOT cause").
  Fix: examples where physical evidence clearly eliminates one specific disjunct,
  and the model must negate THAT one (the one with evidence against it).

Format: same text field as main training data.
Generated by build_supplement() → list[dict].
"""

from __future__ import annotations
from dras.preprocess import _format

# ---------------------------------------------------------------------------
# Noise premises — varied, domain-isolated, clearly irrelevant
# ---------------------------------------------------------------------------
_NOISE = [
    "The cafeteria is open on weekdays from 7am to 3pm.",
    "Parking is available in the basement car park.",
    "The building has security cameras at all entrances.",
    "All visitors must sign in at the reception desk.",
    "The quarterly performance review is scheduled for next month.",
    "The conference room seats up to twelve people.",
    "The printer on the third floor is out of toner.",
    "The annual fire drill occurs in October.",
    "Overtime pay applies after forty hours per week.",
    "The company newsletter is distributed on Fridays.",
    "The roof was repaired following last winter's storm.",
    "Employee ID badges expire every two years.",
    "The water cooler on floor two was serviced last Tuesday.",
    "The backup server is located in a separate building.",
    "Petty cash reimbursements require a signed receipt.",
]


def _n(i: int) -> str:
    return _NOISE[i % len(_NOISE)]


# ---------------------------------------------------------------------------
# B4 FIX: mixed-context instantiation
#
# Pattern: oracle support (2 premises) embedded in 4-premise retrieved set.
# Each example is identical in logic to the oracle ri_ chains,
# but the model must pick the 2 relevant premises from 4.
# ---------------------------------------------------------------------------

def _b4_examples() -> list[dict]:
    rows = []

    def add(goal, premises_4, step):
        rows.append({"text": _format(goal, premises_4, step)})

    # ── Alex / security clearance (B4 benchmark itself) ─────────────────────
    goal = "Alex is not cleared by security."

    add(goal, [
        _n(0),
        "Alex does not hold top-level clearance.",
        "Anyone who can view classified files holds top-level clearance.",
        _n(1),
    ], "Anyone who does not hold top-level clearance cannot view classified files.")

    add(goal, [
        "Anyone who does not hold top-level clearance cannot view classified files.",
        _n(2),
        "Alex does not hold top-level clearance.",
        _n(3),
    ], "Alex cannot view classified files.")

    add(goal, [
        _n(4),
        "Alex cannot view classified files.",
        "Anyone who can access the server room can view the classified files.",
        _n(5),
    ], "Alex cannot access the server room.")

    add(goal, [
        "Alex cannot access the server room.",
        _n(6),
        "Anyone cleared by security can access the server room.",
        _n(7),
    ], "Alex is not cleared by security.")

    # ── Sarah / bar exam ─────────────────────────────────────────────────────
    goal2 = "Sarah is not a licensed attorney."

    add(goal2, [
        _n(8),
        "If someone has not passed the bar exam, they are not a licensed attorney.",
        "Sarah has not passed the bar exam.",
        _n(9),
    ], "Sarah is not a licensed attorney.")

    # ── Officer Blake / flight hours ─────────────────────────────────────────
    goal3 = "Officer Blake is not a certified pilot."

    add(goal3, [
        _n(10),
        "If someone has not logged at least 200 flight hours, they are not a certified pilot.",
        "Officer Blake has not logged 200 flight hours.",
        _n(11),
    ], "Officer Blake is not a certified pilot.")

    # ── Representative Ellis / disclosure ────────────────────────────────────
    goal4 = "Representative Ellis is not an elected official."

    add(goal4, [
        _n(12),
        "If someone has not filed a public financial disclosure, they are not an elected official.",
        "Representative Ellis has not filed a public financial disclosure.",
        _n(13),
    ], "Representative Ellis is not an elected official.")

    # ── Morgan / course enrollment ───────────────────────────────────────────
    goal5 = "Morgan is not a graduate student."

    add(goal5, [
        _n(0),
        "If someone is not enrolled in any course, they are not a graduate student.",
        "Morgan is not enrolled in any course.",
        _n(2),
    ], "Morgan is not a graduate student.")

    # ── Dr. Patel (exact B1 / B4 benchmark wording) with noise ───────────────
    goal6 = "Dr. Patel is not a licensed surgeon."

    add(goal6, [
        _n(4),
        "If someone has not completed a surgical residency, they are not a licensed surgeon.",
        "Dr. Patel has not completed a surgical residency.",
        _n(6),
    ], "Dr. Patel is not a licensed surgeon.")

    # ── Chained rule + instantiation (2-step with noise at each step) ────────
    goal7 = "Director Walsh is not a board member."

    add(goal7, [
        _n(1),
        "Any signatory of the governance charter has attended orientation.",
        "Director Walsh has not attended orientation.",
        _n(8),
    ], "Director Walsh has not signed the governance charter.")

    add(goal7, [
        "Director Walsh has not signed the governance charter.",
        _n(3),
        "All members of the board have signed the governance charter.",
        _n(9),
    ], "Director Walsh is not a member of the board.")

    # ── Agent Torres / clearance (cp_04 with noise) ──────────────────────────
    goal8 = "Agent Torres is not an intelligence analyst."

    add(goal8, [
        _n(5),
        "If someone has not been background-checked, they do not hold a top-secret clearance.",
        "Agent Torres has not been background-checked.",
        _n(10),
    ], "Agent Torres does not hold a top-secret clearance.")

    add(goal8, [
        "Agent Torres does not hold a top-secret clearance.",
        _n(7),
        "All intelligence analysts hold a top-secret clearance.",
        _n(12),
    ], "Agent Torres is not an intelligence analyst.")

    # ── Compound X / clinical trials (mt_03 with noise) ─────────────────────
    goal9 = "Compound X has not been approved by the regulatory body."

    add(goal9, [
        _n(13),
        "If a drug has not passed clinical trials, it has not been approved by the regulatory body.",
        "Compound X has not passed clinical trials.",
        _n(14),
    ], "Compound X has not been approved by the regulatory body.")

    # ── Commissioner Okafor (cp_05 with noise) ───────────────────────────────
    goal10 = "Commissioner Okafor is not an elected official."

    add(goal10, [
        _n(2),
        "If someone has not campaigned in at least three districts, they have not won a majority of votes.",
        "Commissioner Okafor has not campaigned in at least three districts.",
        _n(5),
    ], "Commissioner Okafor has not won a majority of votes.")

    add(goal10, [
        "Commissioner Okafor has not won a majority of votes.",
        _n(8),
        "If someone has not won a majority of votes, they are not an elected official.",
        _n(11),
    ], "Commissioner Okafor is not an elected official.")

    return rows


# ---------------------------------------------------------------------------
# B3 FIX: disjunctive syllogism — correct direction
#
# Pattern: evidence AGAINST disjunct A → "not A" → then "must be B"
# The evidence sentence describes a concrete check on A (not on B).
# Model must negate A (the one with evidence), not B.
# ---------------------------------------------------------------------------

def _b3_examples() -> list[dict]:
    rows = []

    def add(goal, premises, step):
        rows.append({"text": _format(goal, premises, step)})

    # ── B3 exact problem ─────────────────────────────────────────────────────
    goal = "The system will be offline for maintenance."
    seeds = [
        "The network outage was caused by either a hardware fault or a software bug.",
        "All hardware components have been inspected and confirmed fully functional.",
        "If the outage was caused by a software bug, a patch must be deployed.",
        "If a patch must be deployed, the system will be taken offline for maintenance.",
    ]
    # Step 1: evidence eliminates the hardware disjunct
    add(goal, seeds,
        "The network outage was not caused by a hardware fault.")
    # Step 2: disjunction + negation → surviving disjunct
    add(goal, seeds + ["The network outage was not caused by a hardware fault."],
        "The network outage was caused by a software bug.")
    # Step 3 onwards handled by existing ds_fix_05 chain

    # ── Bridge collapse (physical inspection eliminates flooding) ─────────────
    goal2 = "An engineering assessment is required before the bridge can reopen."
    seeds2 = [
        "The bridge closure was caused by either flooding or structural damage.",
        "River gauges recorded normal water levels throughout the closure period.",
        "Structural damage requires an engineering assessment before reopening.",
    ]
    add(goal2, seeds2,
        "There was no flooding.")
    add(goal2, seeds2 + ["There was no flooding."],
        "The bridge closure was caused by structural damage.")
    add(goal2, seeds2 + ["There was no flooding.", "The bridge closure was caused by structural damage."],
        "An engineering assessment is required before the bridge can reopen.")

    # ── Power failure (grid monitoring eliminates overload) ────────────────────
    goal3 = "The substation must be inspected."
    seeds3 = [
        "The power failure was caused by either grid overload or a substation fault.",
        "Grid monitoring confirmed load levels were within normal operating limits.",
        "A substation fault requires immediate inspection.",
    ]
    add(goal3, seeds3,
        "The power failure was not caused by grid overload.")
    add(goal3, seeds3 + ["The power failure was not caused by grid overload."],
        "The power failure was caused by a substation fault.")
    add(goal3, seeds3 + [
        "The power failure was not caused by grid overload.",
        "The power failure was caused by a substation fault.",
    ], "The substation must be inspected.")

    # ── Lab anomaly (sterilization protocol eliminates contamination) ──────────
    goal4 = "The experiment will be repeated."
    seeds4 = [
        "The anomaly resulted from either contamination or instrument calibration error.",
        "All sterilization protocols were followed and independently verified.",
        "Calibration error requires the experiment to be repeated.",
    ]
    add(goal4, seeds4,
        "The anomaly was not caused by contamination.")
    add(goal4, seeds4 + ["The anomaly was not caused by contamination."],
        "The anomaly resulted from instrument calibration error.")
    add(goal4, seeds4 + [
        "The anomaly was not caused by contamination.",
        "The anomaly resulted from instrument calibration error.",
    ], "The experiment will be repeated.")

    # ── Contract dispute (legal review eliminates ambiguous wording) ───────────
    goal5 = "The aggrieved party is entitled to seek damages."
    seeds5 = [
        "The dispute arose from either ambiguous contract wording or a breach of terms.",
        "Legal counsel confirmed all disputed clauses are unambiguous.",
        "A breach of terms entitles the aggrieved party to seek damages.",
    ]
    add(goal5, seeds5,
        "The dispute did not arise from ambiguous contract wording.")
    add(goal5, seeds5 + ["The dispute did not arise from ambiguous contract wording."],
        "The dispute arose from a breach of terms.")
    add(goal5, seeds5 + [
        "The dispute did not arise from ambiguous contract wording.",
        "The dispute arose from a breach of terms.",
    ], "The aggrieved party is entitled to seek damages.")

    return rows


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_supplement() -> list[dict]:
    """Returns all targeted supplement examples."""
    b4 = _b4_examples()
    b3 = _b3_examples()
    return b4 + b3
