"""
Synthetic multi-step chain training data.

Each chain defines: seeds (given premises), goal (final conclusion),
and steps (ordered intermediate derivations, last one == goal).

Training examples are generated by the masking procedure:
  for step k: premises = seeds + steps[0..k-1], target = steps[k]

This teaches the model to produce ONE valid intermediate step at a time,
not jump directly to the conclusion — the key capability gap in FOLIO-only training.

Patterns covered:
  modus_ponens_chain      — forward chaining A→B→C→...→Goal
  modus_tollens           — contrapositive instantiation
  contrapositive_chain    — chained modus tollens, working backwards
  disjunctive_syllogism   — A∨B, ¬A ∴ B
  hypothetical_syllogism  — P→Q, Q→R ∴ P→R (with instantiation)
  mixed                   — combinations of the above
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Chain definitions
# ---------------------------------------------------------------------------

CHAINS: list[dict] = [

    # ── MODUS PONENS CHAINS ──────────────────────────────────────────────────

    {
        "id": "mp_01", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any patient with a temperature over 38.5 degrees Celsius has a fever.",
            "Any patient with a fever is assessed by a triage nurse.",
            "Any patient assessed by a triage nurse receives a priority wristband.",
            "Lucas has a temperature of 39 degrees Celsius.",
        ],
        "goal": "Lucas has received a priority wristband.",
        "steps": [
            "Lucas has a fever.",
            "Lucas is assessed by a triage nurse.",
            "Lucas has received a priority wristband.",
        ],
    },
    {
        "id": "mp_02", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any code that passes all unit tests is approved for staging.",
            "Any code approved for staging is reviewed by a senior engineer.",
            "Any code reviewed by a senior engineer can be deployed to production.",
            "The authentication module has passed all unit tests.",
        ],
        "goal": "The authentication module can be deployed to production.",
        "steps": [
            "The authentication module is approved for staging.",
            "The authentication module is reviewed by a senior engineer.",
            "The authentication module can be deployed to production.",
        ],
    },
    {
        "id": "mp_03", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any factory that exceeds its emissions limit violates environmental regulations.",
            "Any factory violating environmental regulations is subject to fines.",
            "Any factory subject to fines must submit a compliance remediation plan.",
            "The Greenfield factory exceeded its emissions limit last quarter.",
        ],
        "goal": "The Greenfield factory must submit a compliance remediation plan.",
        "steps": [
            "The Greenfield factory violated environmental regulations.",
            "The Greenfield factory is subject to fines.",
            "The Greenfield factory must submit a compliance remediation plan.",
        ],
    },
    {
        "id": "mp_04", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any employee who misses three or more consecutive meetings is flagged for review.",
            "Any employee flagged for review must meet with their direct manager.",
            "Any employee who meets with their manager following a flag receives a performance improvement plan.",
            "Any employee on a performance improvement plan has their system access restricted.",
            "Priya has missed four consecutive meetings.",
        ],
        "goal": "Priya's system access has been restricted.",
        "steps": [
            "Priya has been flagged for review.",
            "Priya must meet with her direct manager.",
            "Priya has received a performance improvement plan.",
            "Priya's system access has been restricted.",
        ],
    },
    {
        "id": "mp_05", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any supplier that meets ISO 9001 standards is certified.",
            "Any certified supplier is included on the approved vendor list.",
            "Any supplier on the approved vendor list is eligible to receive purchase orders.",
            "Meridian Supplies has met ISO 9001 standards.",
        ],
        "goal": "Meridian Supplies is eligible to receive purchase orders.",
        "steps": [
            "Meridian Supplies is certified.",
            "Meridian Supplies is included on the approved vendor list.",
            "Meridian Supplies is eligible to receive purchase orders.",
        ],
    },
    {
        "id": "mp_06", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any data breach triggers an incident response protocol.",
            "Any incident response protocol requires notifying the chief security officer.",
            "Any notification to the chief security officer initiates a full system audit.",
            "A full system audit produces a vulnerability report.",
            "A data breach occurred on the payroll server.",
        ],
        "goal": "A vulnerability report has been produced.",
        "steps": [
            "An incident response protocol has been triggered.",
            "The chief security officer has been notified.",
            "A full system audit has been initiated.",
            "A vulnerability report has been produced.",
        ],
    },
    {
        "id": "mp_07", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any student who fails two or more courses is placed on academic probation.",
            "Any student on academic probation is barred from joining extracurricular clubs.",
            "Any student barred from clubs loses their campus activity fee credit.",
            "Marco failed three courses this semester.",
        ],
        "goal": "Marco has lost his campus activity fee credit.",
        "steps": [
            "Marco is placed on academic probation.",
            "Marco is barred from joining extracurricular clubs.",
            "Marco has lost his campus activity fee credit.",
        ],
    },
    {
        "id": "mp_08", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any manuscript that passes peer review is accepted for publication.",
            "Any accepted manuscript is assigned to a copy editor.",
            "Any manuscript assigned to a copy editor is formatted for the press.",
            "Any formatted manuscript is sent to the printer.",
            "Vasquez's manuscript has passed peer review.",
        ],
        "goal": "Vasquez's manuscript has been sent to the printer.",
        "steps": [
            "Vasquez's manuscript has been accepted for publication.",
            "Vasquez's manuscript has been assigned to a copy editor.",
            "Vasquez's manuscript has been formatted for the press.",
            "Vasquez's manuscript has been sent to the printer.",
        ],
    },
    {
        "id": "mp_09", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any employee who completes safety training takes a certification exam.",
            "Any employee who passes the certification exam receives a safety badge.",
            "Any employee with a safety badge is authorized to operate heavy machinery.",
            "Rivera completed the full safety training program.",
        ],
        "goal": "Rivera is authorized to operate heavy machinery.",
        "steps": [
            "Rivera took the certification exam.",
            "Rivera received a safety badge.",
            "Rivera is authorized to operate heavy machinery.",
        ],
    },
    {
        "id": "mp_10", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any nation that ratifies the climate accord must reduce emissions by 30 percent.",
            "Any nation that reduces emissions by 30 percent qualifies for green technology grants.",
            "Any nation qualifying for green technology grants gains access to low-interest loans.",
            "Any nation with access to low-interest loans can fund renewable energy projects.",
            "Any nation funding renewable energy projects attracts international investment.",
            "Verdania ratified the climate accord.",
        ],
        "goal": "Verdania attracts international investment.",
        "steps": [
            "Verdania must reduce emissions by 30 percent.",
            "Verdania qualifies for green technology grants.",
            "Verdania gains access to low-interest loans.",
            "Verdania can fund renewable energy projects.",
            "Verdania attracts international investment.",
        ],
    },
    {
        "id": "mp_11", "pattern": "modus_ponens_chain",
        "seeds": [
            "Any contract signed under duress is voidable.",
            "Any voidable contract can be challenged in court.",
            "Any contract that can be challenged in court requires legal representation.",
            "Any contract requiring legal representation incurs legal fees.",
            "The employment contract was signed under duress.",
        ],
        "goal": "The employment contract will incur legal fees.",
        "steps": [
            "The employment contract is voidable.",
            "The employment contract can be challenged in court.",
            "The employment contract requires legal representation.",
            "The employment contract will incur legal fees.",
        ],
    },
    {
        "id": "mp_12", "pattern": "modus_ponens_chain",
        "seeds": [
            "Anyone who registers for the conference receives a participant badge.",
            "Anyone with a participant badge can access the exhibition hall.",
            "Anyone who accesses the exhibition hall is logged in the attendance register.",
            "Yuki registered for the conference.",
        ],
        "goal": "Yuki is logged in the attendance register.",
        "steps": [
            "Yuki received a participant badge.",
            "Yuki can access the exhibition hall.",
            "Yuki is logged in the attendance register.",
        ],
    },

    # ── MODUS TOLLENS / CONTRAPOSITIVE ───────────────────────────────────────

    {
        "id": "mt_01", "pattern": "modus_tollens",
        "seeds": [
            "Any vehicle that passes the safety inspection receives a roadworthy certificate.",
            "This vehicle has not received a roadworthy certificate.",
        ],
        "goal": "This vehicle did not pass the safety inspection.",
        "steps": [
            "If a vehicle has not received a roadworthy certificate, it did not pass the safety inspection.",
            "This vehicle did not pass the safety inspection.",
        ],
    },
    {
        "id": "mt_02", "pattern": "modus_tollens",
        "seeds": [
            "All licensed surgeons have completed a surgical residency.",
            "Dr. Patel has not completed a surgical residency.",
        ],
        "goal": "Dr. Patel is not a licensed surgeon.",
        "steps": [
            "If someone has not completed a surgical residency, they are not a licensed surgeon.",
            "Dr. Patel is not a licensed surgeon.",
        ],
    },
    {
        "id": "mt_03", "pattern": "modus_tollens",
        "seeds": [
            "Any drug approved by the regulatory body has passed clinical trials.",
            "Compound X has not passed clinical trials.",
        ],
        "goal": "Compound X has not been approved by the regulatory body.",
        "steps": [
            "If a drug has not passed clinical trials, it has not been approved by the regulatory body.",
            "Compound X has not been approved by the regulatory body.",
        ],
    },
    {
        "id": "mt_04", "pattern": "modus_tollens",
        "seeds": [
            "Any software that passes quality assurance testing is released to production.",
            "The inventory module has not been released to production.",
        ],
        "goal": "The inventory module did not pass quality assurance testing.",
        "steps": [
            "If software has not been released to production, it did not pass quality assurance testing.",
            "The inventory module did not pass quality assurance testing.",
        ],
    },
    {
        "id": "mt_05", "pattern": "modus_tollens",
        "seeds": [
            "Every board member voted on the merger proposal.",
            "Director Chen did not vote on the merger proposal.",
        ],
        "goal": "Director Chen is not a board member.",
        "steps": [
            "If someone did not vote on the merger proposal, they are not a board member.",
            "Director Chen is not a board member.",
        ],
    },

    # ── CONTRAPOSITIVE CHAINS ────────────────────────────────────────────────

    {
        "id": "cp_01", "pattern": "contrapositive_chain",
        "seeds": [
            "All board members have signed the conflict of interest disclosure.",
            "All signatories of the disclosure have passed a background check.",
            "Director Walsh has not passed a background check.",
        ],
        "goal": "Director Walsh is not a board member.",
        "steps": [
            "If someone has not passed a background check, they have not signed the conflict of interest disclosure.",
            "Director Walsh has not signed the conflict of interest disclosure.",
            "If someone has not signed the conflict of interest disclosure, they are not a board member.",
            "Director Walsh is not a board member.",
        ],
    },
    {
        "id": "cp_02", "pattern": "contrapositive_chain",
        "seeds": [
            "Anyone admitted to the graduate program holds an undergraduate degree.",
            "Anyone holding an undergraduate degree has completed at least four years of study.",
            "Dr. Rivera has not completed four years of study.",
        ],
        "goal": "Dr. Rivera has not been admitted to the graduate program.",
        "steps": [
            "If someone has not completed four years of study, they do not hold an undergraduate degree.",
            "Dr. Rivera does not hold an undergraduate degree.",
            "If someone does not hold an undergraduate degree, they have not been admitted to the graduate program.",
            "Dr. Rivera has not been admitted to the graduate program.",
        ],
    },
    {
        "id": "cp_03", "pattern": "contrapositive_chain",
        "seeds": [
            "Anyone cleared by security can access the server room.",
            "Anyone who can access the server room can view the classified files.",
            "Anyone who can view classified files holds top-level clearance.",
            "Alex does not hold top-level clearance.",
        ],
        "goal": "Alex is not cleared by security.",
        "steps": [
            "Anyone who does not hold top-level clearance cannot view classified files.",
            "Alex cannot view classified files.",
            "Anyone who cannot view classified files cannot access the server room.",
            "Alex cannot access the server room.",
            "Anyone who cannot access the server room is not cleared by security.",
            "Alex is not cleared by security.",
        ],
    },
    {
        "id": "cp_04", "pattern": "contrapositive_chain",
        "seeds": [
            "All intelligence analysts hold a top-secret clearance.",
            "All holders of top-secret clearance have been background-checked.",
            "Agent Torres has not been background-checked.",
        ],
        "goal": "Agent Torres is not an intelligence analyst.",
        "steps": [
            "If someone has not been background-checked, they do not hold a top-secret clearance.",
            "Agent Torres does not hold a top-secret clearance.",
            "If someone does not hold a top-secret clearance, they are not an intelligence analyst.",
            "Agent Torres is not an intelligence analyst.",
        ],
    },
    {
        "id": "cp_05", "pattern": "contrapositive_chain",
        "seeds": [
            "Any elected official has won a majority of votes.",
            "Anyone who wins a majority of votes has campaigned in at least three districts.",
            "Commissioner Okafor has not campaigned in at least three districts.",
        ],
        "goal": "Commissioner Okafor is not an elected official.",
        "steps": [
            "If someone has not campaigned in at least three districts, they have not won a majority of votes.",
            "Commissioner Okafor has not won a majority of votes.",
            "If someone has not won a majority of votes, they are not an elected official.",
            "Commissioner Okafor is not an elected official.",
        ],
    },

    # ── DISJUNCTIVE SYLLOGISM ────────────────────────────────────────────────

    {
        "id": "ds_01", "pattern": "disjunctive_syllogism",
        "seeds": [
            "The power failure was caused by either a grid overload or a substation fault.",
            "The grid was operating within normal capacity during the failure.",
            "A substation fault triggers an automatic safety shutdown.",
        ],
        "goal": "An automatic safety shutdown has been triggered.",
        "steps": [
            "The power failure was caused by a substation fault.",
            "An automatic safety shutdown has been triggered.",
        ],
    },
    {
        "id": "ds_02", "pattern": "disjunctive_syllogism",
        "seeds": [
            "The data loss was caused by either a hardware failure or human error.",
            "Hardware diagnostics confirm all drives are functioning normally.",
            "If the data loss was caused by human error, a disciplinary review will be initiated.",
            "A disciplinary review results in a formal written warning.",
        ],
        "goal": "A formal written warning will be issued.",
        "steps": [
            "The data loss was caused by human error.",
            "A disciplinary review will be initiated.",
            "A formal written warning will be issued.",
        ],
    },
    {
        "id": "ds_03", "pattern": "disjunctive_syllogism",
        "seeds": [
            "The experimental anomaly was due to either contamination or measurement error.",
            "Rigorous sterilization protocols were followed, ruling out contamination.",
            "Measurement error requires the experiment to be repeated.",
            "Experiments that must be repeated are removed from the preliminary dataset.",
        ],
        "goal": "The experiment has been removed from the preliminary dataset.",
        "steps": [
            "The experimental anomaly was due to measurement error.",
            "The experiment must be repeated.",
            "The experiment has been removed from the preliminary dataset.",
        ],
    },
    {
        "id": "ds_04", "pattern": "disjunctive_syllogism",
        "seeds": [
            "The shipment delay was due to either customs clearance issues or a logistics error.",
            "Customs confirmed the shipment cleared all checks without issues.",
            "A logistics error requires a formal incident report to be filed.",
            "A formal incident report triggers a supplier audit.",
        ],
        "goal": "A supplier audit has been triggered.",
        "steps": [
            "The shipment delay was due to a logistics error.",
            "A formal incident report has been filed.",
            "A supplier audit has been triggered.",
        ],
    },
    {
        "id": "ds_05", "pattern": "disjunctive_syllogism",
        "seeds": [
            "The bridge damage was caused by either flooding or structural fatigue.",
            "No flooding was reported in the region during the damage period.",
            "Structural fatigue causes microcracks to propagate through the load-bearing supports.",
            "Microcracks in load-bearing supports require an immediate engineering assessment.",
        ],
        "goal": "An immediate engineering assessment is required.",
        "steps": [
            "The bridge damage was caused by structural fatigue.",
            "Microcracks are propagating through the load-bearing supports.",
            "An immediate engineering assessment is required.",
        ],
    },

    # ── MIXED PATTERNS ───────────────────────────────────────────────────────

    {
        "id": "mx_01", "pattern": "mixed",
        "seeds": [
            "All interns who complete the project are offered a full-time position.",
            "All employees offered a full-time position must sign an employment contract.",
            "Any contract signing requires a background check to be completed first.",
            "Rivera completed the internship project.",
        ],
        "goal": "Rivera must complete a background check.",
        "steps": [
            "Rivera has been offered a full-time position.",
            "Rivera must sign an employment contract.",
            "Rivera must complete a background check.",
        ],
    },
    {
        "id": "mx_02", "pattern": "mixed",
        "seeds": [
            "Every witness who testifies truthfully is protected under the witness protection act.",
            "Witness Morrison is not protected under the witness protection act.",
            "Any testimony containing false statements is stricken from the record.",
            "Testimony stricken from the record cannot influence the verdict.",
        ],
        "goal": "Witness Morrison's testimony cannot influence the verdict.",
        "steps": [
            "If a witness is not protected under the witness protection act, they did not testify truthfully.",
            "Witness Morrison did not testify truthfully.",
            "Witness Morrison's testimony contains false statements.",
            "Witness Morrison's testimony has been stricken from the record.",
            "Witness Morrison's testimony cannot influence the verdict.",
        ],
    },
    {
        "id": "mx_03", "pattern": "mixed",
        "seeds": [
            "The trial is invalid if any juror has a direct conflict of interest.",
            "A juror who is a business partner of the defendant has a direct conflict of interest.",
            "Juror 7 is the defendant's business partner.",
            "Any invalid trial must be declared a mistrial.",
            "A mistrial requires all proceedings to be restarted from jury selection.",
        ],
        "goal": "All proceedings must be restarted from jury selection.",
        "steps": [
            "Juror 7 has a direct conflict of interest.",
            "The trial is invalid.",
            "The trial must be declared a mistrial.",
            "All proceedings must be restarted from jury selection.",
        ],
    },
    {
        "id": "mx_04", "pattern": "mixed",
        "seeds": [
            "The network outage was caused by either hardware failure or a software bug.",
            "All hardware has been certified as fully operational.",
            "A software bug requires the engineering team to issue a patch.",
            "Any issued patch must pass regression testing before deployment.",
            "Any patch that passes regression testing is deployed within 24 hours.",
        ],
        "goal": "A patch will be deployed within 24 hours.",
        "steps": [
            "The network outage was caused by a software bug.",
            "The engineering team must issue a patch.",
            "The patch must pass regression testing before deployment.",
            "A patch will be deployed within 24 hours.",
        ],
    },
    {
        "id": "mx_05", "pattern": "mixed",
        "seeds": [
            "All patients admitted to the ICU are classified as critical.",
            "All critical patients receive hourly monitoring.",
            "All patients receiving hourly monitoring are assigned a dedicated nurse.",
            "Patient Jordan was admitted to the ICU.",
            "Any patient with a dedicated nurse has their family notified immediately.",
        ],
        "goal": "Patient Jordan's family has been notified.",
        "steps": [
            "Patient Jordan is classified as critical.",
            "Patient Jordan receives hourly monitoring.",
            "Patient Jordan has been assigned a dedicated nurse.",
            "Patient Jordan's family has been notified.",
        ],
    },
    {
        "id": "mx_06", "pattern": "mixed",
        "seeds": [
            "All mammals are warm-blooded.",
            "All warm-blooded animals regulate their own body temperature.",
            "Snakes do not regulate their own body temperature.",
        ],
        "goal": "Snakes are not mammals.",
        "steps": [
            "If an animal does not regulate its own body temperature, it is not warm-blooded.",
            "Snakes are not warm-blooded.",
            "If an animal is not warm-blooded, it is not a mammal.",
            "Snakes are not mammals.",
        ],
    },
    {
        "id": "mx_07", "pattern": "mixed",
        "seeds": [
            "All members of the research team have signed the data confidentiality agreement.",
            "Anyone who has signed the confidentiality agreement is legally bound to non-disclosure.",
            "Anyone legally bound to non-disclosure cannot publish the raw data.",
            "Professor Kim is a member of the research team.",
        ],
        "goal": "Professor Kim cannot publish the raw data.",
        "steps": [
            "Professor Kim has signed the data confidentiality agreement.",
            "Professor Kim is legally bound to non-disclosure.",
            "Professor Kim cannot publish the raw data.",
        ],
    },
    {
        "id": "mx_08", "pattern": "mixed",
        "seeds": [
            "Any nation that signs the trade agreement reduces import tariffs.",
            "Any nation that reduces import tariffs sees an increase in foreign goods.",
            "Any nation that sees an increase in foreign goods experiences greater consumer choice.",
            "Any nation experiencing greater consumer choice sees downward pressure on domestic prices.",
            "Altoria signed the trade agreement.",
        ],
        "goal": "Altoria will see downward pressure on domestic prices.",
        "steps": [
            "Altoria will reduce import tariffs.",
            "Altoria will see an increase in foreign goods.",
            "Altoria will experience greater consumer choice.",
            "Altoria will see downward pressure on domestic prices.",
        ],
    },
    {
        "id": "mx_09", "pattern": "mixed",
        "seeds": [
            "Any proposal that fails the feasibility review is rejected.",
            "Any rejected proposal requires a resubmission with revised cost estimates.",
            "Any resubmission with revised estimates is reviewed by the oversight committee.",
            "The solar farm proposal failed the feasibility review.",
            "Any proposal reviewed by the oversight committee gets a final binding decision.",
        ],
        "goal": "The solar farm proposal will receive a final binding decision.",
        "steps": [
            "The solar farm proposal has been rejected.",
            "The solar farm proposal requires a resubmission with revised cost estimates.",
            "The resubmission will be reviewed by the oversight committee.",
            "The solar farm proposal will receive a final binding decision.",
        ],
    },
    {
        "id": "mx_10", "pattern": "mixed",
        "seeds": [
            "The alarm was either triggered by motion detection or by a manual activation.",
            "The motion detection system was offline during the incident.",
            "A manually activated alarm requires an incident log entry.",
            "An incident log entry must be reviewed by the security supervisor.",
            "Any item reviewed by the security supervisor is included in the monthly report.",
        ],
        "goal": "The alarm activation will be included in the monthly report.",
        "steps": [
            "The alarm was triggered by a manual activation.",
            "An incident log entry is required.",
            "The incident log entry must be reviewed by the security supervisor.",
            "The alarm activation will be included in the monthly report.",
        ],
    },
]

# ---------------------------------------------------------------------------
# Annotated chains — each step carries explicit `support` premises.
# These generate ORACLE training examples (model sees only the 2-3 premises
# that directly support the step, not the full accumulated store).
# Also used for contrastive retriever training.
#
# Patterns targeted: rule_instantiation (fixes B1), disjunctive_syllogism_explicit (fixes B3)
# ---------------------------------------------------------------------------

ANNOTATED_CHAINS: list[dict] = [

    # ── RULE INSTANTIATION (B1 fix) ──────────────────────────────────────────
    # Pattern: form contrapositive rule → apply rule to specific entity
    # Model must learn: rule + entity fact → entity conclusion (not another rule)

    {
        "id": "ri_01", "pattern": "rule_instantiation",
        "seeds": [
            "All licensed attorneys have passed the bar exam.",
            "Sarah has not passed the bar exam.",
        ],
        "goal": "Sarah is not a licensed attorney.",
        "steps": [
            {
                "text": "If someone has not passed the bar exam, they are not a licensed attorney.",
                "support": ["All licensed attorneys have passed the bar exam."],
            },
            {
                "text": "Sarah is not a licensed attorney.",
                "support": [
                    "If someone has not passed the bar exam, they are not a licensed attorney.",
                    "Sarah has not passed the bar exam.",
                ],
            },
        ],
    },
    {
        "id": "ri_02", "pattern": "rule_instantiation",
        "seeds": [
            "All certified pilots have logged at least 200 flight hours.",
            "Officer Blake has not logged 200 flight hours.",
        ],
        "goal": "Officer Blake is not a certified pilot.",
        "steps": [
            {
                "text": "If someone has not logged at least 200 flight hours, they are not a certified pilot.",
                "support": ["All certified pilots have logged at least 200 flight hours."],
            },
            {
                "text": "Officer Blake is not a certified pilot.",
                "support": [
                    "If someone has not logged at least 200 flight hours, they are not a certified pilot.",
                    "Officer Blake has not logged 200 flight hours.",
                ],
            },
        ],
    },
    {
        "id": "ri_03", "pattern": "rule_instantiation",
        "seeds": [
            "Any vaccine approved by the health authority has completed phase three trials.",
            "Compound V has not completed phase three trials.",
        ],
        "goal": "Compound V has not been approved by the health authority.",
        "steps": [
            {
                "text": "If a vaccine has not completed phase three trials, it has not been approved by the health authority.",
                "support": ["Any vaccine approved by the health authority has completed phase three trials."],
            },
            {
                "text": "Compound V has not been approved by the health authority.",
                "support": [
                    "If a vaccine has not completed phase three trials, it has not been approved by the health authority.",
                    "Compound V has not completed phase three trials.",
                ],
            },
        ],
    },
    {
        "id": "ri_04", "pattern": "rule_instantiation",
        "seeds": [
            "Every elected official has filed a public financial disclosure.",
            "Representative Ellis has not filed a public financial disclosure.",
        ],
        "goal": "Representative Ellis is not an elected official.",
        "steps": [
            {
                "text": "If someone has not filed a public financial disclosure, they are not an elected official.",
                "support": ["Every elected official has filed a public financial disclosure."],
            },
            {
                "text": "Representative Ellis is not an elected official.",
                "support": [
                    "If someone has not filed a public financial disclosure, they are not an elected official.",
                    "Representative Ellis has not filed a public financial disclosure.",
                ],
            },
        ],
    },
    {
        "id": "ri_05", "pattern": "rule_instantiation",
        "seeds": [
            "All graduate students are enrolled in at least one course.",
            "Morgan is not enrolled in any course.",
        ],
        "goal": "Morgan is not a graduate student.",
        "steps": [
            {
                "text": "If someone is not enrolled in any course, they are not a graduate student.",
                "support": ["All graduate students are enrolled in at least one course."],
            },
            {
                "text": "Morgan is not a graduate student.",
                "support": [
                    "If someone is not enrolled in any course, they are not a graduate student.",
                    "Morgan is not enrolled in any course.",
                ],
            },
        ],
    },
    {
        "id": "ri_06", "pattern": "rule_instantiation",
        "seeds": [
            "All members of the board have signed the governance charter.",
            "Any signatory of the governance charter has attended orientation.",
            "Director Vance has not attended orientation.",
        ],
        "goal": "Director Vance is not a member of the board.",
        "steps": [
            {
                "text": "If someone has not attended orientation, they have not signed the governance charter.",
                "support": ["Any signatory of the governance charter has attended orientation."],
            },
            {
                "text": "Director Vance has not signed the governance charter.",
                "support": [
                    "If someone has not attended orientation, they have not signed the governance charter.",
                    "Director Vance has not attended orientation.",
                ],
            },
            {
                "text": "If someone has not signed the governance charter, they are not a member of the board.",
                "support": ["All members of the board have signed the governance charter."],
            },
            {
                "text": "Director Vance is not a member of the board.",
                "support": [
                    "If someone has not signed the governance charter, they are not a member of the board.",
                    "Director Vance has not signed the governance charter.",
                ],
            },
        ],
    },
    {
        "id": "ri_07", "pattern": "rule_instantiation",
        "seeds": [
            "All ships that pass inspection receive a seaworthiness certificate.",
            "Any ship with a seaworthiness certificate is cleared for international voyages.",
            "The Meridian Star has not been cleared for international voyages.",
        ],
        "goal": "The Meridian Star did not pass inspection.",
        "steps": [
            {
                "text": "If a ship has not been cleared for international voyages, it does not have a seaworthiness certificate.",
                "support": ["Any ship with a seaworthiness certificate is cleared for international voyages."],
            },
            {
                "text": "The Meridian Star does not have a seaworthiness certificate.",
                "support": [
                    "If a ship has not been cleared for international voyages, it does not have a seaworthiness certificate.",
                    "The Meridian Star has not been cleared for international voyages.",
                ],
            },
            {
                "text": "If a ship does not have a seaworthiness certificate, it did not pass inspection.",
                "support": ["All ships that pass inspection receive a seaworthiness certificate."],
            },
            {
                "text": "The Meridian Star did not pass inspection.",
                "support": [
                    "If a ship does not have a seaworthiness certificate, it did not pass inspection.",
                    "The Meridian Star does not have a seaworthiness certificate.",
                ],
            },
        ],
    },
    {
        "id": "ri_08", "pattern": "rule_instantiation",
        "seeds": [
            "All surgical residents have completed medical school.",
            "Dr. Patel has not completed a surgical residency.",
        ],
        "goal": "Dr. Patel is not a licensed surgeon.",
        "steps": [
            {
                "text": "If someone has not completed a surgical residency, they are not a licensed surgeon.",
                "support": ["All surgical residents have completed medical school.",
                            "Dr. Patel has not completed a surgical residency."],
            },
            {
                "text": "Dr. Patel is not a licensed surgeon.",
                "support": [
                    "If someone has not completed a surgical residency, they are not a licensed surgeon.",
                    "Dr. Patel has not completed a surgical residency.",
                ],
            },
        ],
    },

    # ── DISJUNCTIVE SYLLOGISM — EXPLICIT ELIMINATION (B3 fix) ────────────────
    # Pattern: negate one disjunct explicitly → conclude the other
    # Model must learn: evidence-against-A → not-A → B (two clean steps, not one jump)

    {
        "id": "ds_fix_01", "pattern": "disjunctive_syllogism_explicit",
        "seeds": [
            "The system failure was caused by either a software fault or a hardware fault.",
            "A complete hardware diagnostic found no faults in any component.",
        ],
        "goal": "The system failure was caused by a software fault.",
        "steps": [
            {
                "text": "There was no hardware fault.",
                "support": ["A complete hardware diagnostic found no faults in any component."],
            },
            {
                "text": "The system failure was caused by a software fault.",
                "support": [
                    "The system failure was caused by either a software fault or a hardware fault.",
                    "There was no hardware fault.",
                ],
            },
        ],
    },
    {
        "id": "ds_fix_02", "pattern": "disjunctive_syllogism_explicit",
        "seeds": [
            "The patient's condition worsened due to either an incorrect diagnosis or a medication error.",
            "Three independent physicians reviewed the case and confirmed the diagnosis was correct.",
            "A medication error requires an immediate incident report.",
        ],
        "goal": "An incident report must be filed immediately.",
        "steps": [
            {
                "text": "The diagnosis was not incorrect.",
                "support": ["Three independent physicians reviewed the case and confirmed the diagnosis was correct."],
            },
            {
                "text": "The patient's condition worsened due to a medication error.",
                "support": [
                    "The patient's condition worsened due to either an incorrect diagnosis or a medication error.",
                    "The diagnosis was not incorrect.",
                ],
            },
            {
                "text": "An incident report must be filed immediately.",
                "support": [
                    "The patient's condition worsened due to a medication error.",
                    "A medication error requires an immediate incident report.",
                ],
            },
        ],
    },
    {
        "id": "ds_fix_03", "pattern": "disjunctive_syllogism_explicit",
        "seeds": [
            "The missing funds were either embezzled or lost due to accounting error.",
            "An independent audit confirmed all accounting procedures were followed correctly.",
            "Embezzlement of company funds triggers a mandatory police report.",
            "A mandatory police report initiates a criminal investigation.",
        ],
        "goal": "A criminal investigation has been initiated.",
        "steps": [
            {
                "text": "The funds were not lost due to accounting error.",
                "support": ["An independent audit confirmed all accounting procedures were followed correctly."],
            },
            {
                "text": "The missing funds were embezzled.",
                "support": [
                    "The missing funds were either embezzled or lost due to accounting error.",
                    "The funds were not lost due to accounting error.",
                ],
            },
            {
                "text": "A mandatory police report has been triggered.",
                "support": [
                    "The missing funds were embezzled.",
                    "Embezzlement of company funds triggers a mandatory police report.",
                ],
            },
            {
                "text": "A criminal investigation has been initiated.",
                "support": [
                    "A mandatory police report has been triggered.",
                    "A mandatory police report initiates a criminal investigation.",
                ],
            },
        ],
    },
    {
        "id": "ds_fix_04", "pattern": "disjunctive_syllogism_explicit",
        "seeds": [
            "The bridge closure was caused by either flooding or structural damage.",
            "River gauges recorded normal water levels throughout the closure period.",
            "Structural damage requires an engineering assessment before reopening.",
        ],
        "goal": "An engineering assessment is required before the bridge can reopen.",
        "steps": [
            {
                "text": "There was no flooding.",
                "support": ["River gauges recorded normal water levels throughout the closure period."],
            },
            {
                "text": "The bridge closure was caused by structural damage.",
                "support": [
                    "The bridge closure was caused by either flooding or structural damage.",
                    "There was no flooding.",
                ],
            },
            {
                "text": "An engineering assessment is required before the bridge can reopen.",
                "support": [
                    "The bridge closure was caused by structural damage.",
                    "Structural damage requires an engineering assessment before reopening.",
                ],
            },
        ],
    },
    {
        "id": "ds_fix_05", "pattern": "disjunctive_syllogism_explicit",
        "seeds": [
            "The network outage was caused by either a hardware fault or a software bug.",
            "All hardware components have been inspected and confirmed fully functional.",
            "A software bug requires the deployment of a patch.",
            "Deploying a patch takes the system offline for maintenance.",
        ],
        "goal": "The system will be offline for maintenance.",
        "steps": [
            {
                "text": "The network outage was not caused by a hardware fault.",
                "support": ["All hardware components have been inspected and confirmed fully functional."],
            },
            {
                "text": "The network outage was caused by a software bug.",
                "support": [
                    "The network outage was caused by either a hardware fault or a software bug.",
                    "The network outage was not caused by a hardware fault.",
                ],
            },
            {
                "text": "A patch must be deployed.",
                "support": [
                    "The network outage was caused by a software bug.",
                    "A software bug requires the deployment of a patch.",
                ],
            },
            {
                "text": "The system will be offline for maintenance.",
                "support": [
                    "A patch must be deployed.",
                    "Deploying a patch takes the system offline for maintenance.",
                ],
            },
        ],
    },
    {
        "id": "ds_fix_06", "pattern": "disjunctive_syllogism_explicit",
        "seeds": [
            "The contract dispute arose from either ambiguous wording or a breach of terms.",
            "Legal counsel confirmed the contract language is unambiguous on all contested points.",
            "A breach of terms entitles the aggrieved party to seek damages.",
        ],
        "goal": "The aggrieved party is entitled to seek damages.",
        "steps": [
            {
                "text": "The dispute did not arise from ambiguous wording.",
                "support": ["Legal counsel confirmed the contract language is unambiguous on all contested points."],
            },
            {
                "text": "The contract dispute arose from a breach of terms.",
                "support": [
                    "The contract dispute arose from either ambiguous wording or a breach of terms.",
                    "The dispute did not arise from ambiguous wording.",
                ],
            },
            {
                "text": "The aggrieved party is entitled to seek damages.",
                "support": [
                    "The contract dispute arose from a breach of terms.",
                    "A breach of terms entitles the aggrieved party to seek damages.",
                ],
            },
        ],
    },

    # ── DS FIX: EQUIPMENT/PROTOCOL VOCABULARY (B8 domain) ────────────────────
    # Model must learn: "devices confirmed within normal parameters" → eliminate
    # equipment disjunct, not the goal-proximate protocol-violation disjunct.

    {
        "id": "ds_fix_07", "pattern": "disjunctive_syllogism_explicit",
        "seeds": [
            "The research halt was caused by either equipment malfunction or a protocol violation.",
            "A post-incident equipment inspection confirmed all devices were functioning within normal parameters.",
            "If the halt was caused by a protocol violation, the lead researcher must file an incident report.",
            "If an incident report is filed, the ethics committee conducts a review.",
            "If the ethics committee conducts a review, all non-essential operations at the facility are suspended pending findings.",
        ],
        "goal": "All non-essential operations at the facility have been suspended.",
        "steps": [
            {
                "text": "The research halt was not caused by equipment malfunction.",
                "support": ["A post-incident equipment inspection confirmed all devices were functioning within normal parameters."],
            },
            {
                "text": "The research halt was caused by a protocol violation.",
                "support": [
                    "The research halt was caused by either equipment malfunction or a protocol violation.",
                    "The research halt was not caused by equipment malfunction.",
                ],
            },
            {
                "text": "The lead researcher must file an incident report.",
                "support": [
                    "The research halt was caused by a protocol violation.",
                    "If the halt was caused by a protocol violation, the lead researcher must file an incident report.",
                ],
            },
            {
                "text": "The ethics committee must conduct a review.",
                "support": [
                    "The lead researcher must file an incident report.",
                    "If an incident report is filed, the ethics committee conducts a review.",
                ],
            },
            {
                "text": "All non-essential operations at the facility have been suspended.",
                "support": [
                    "The ethics committee must conduct a review.",
                    "If the ethics committee conducts a review, all non-essential operations at the facility are suspended pending findings.",
                ],
            },
        ],
    },

    {
        "id": "ds_fix_08", "pattern": "disjunctive_syllogism_explicit",
        "seeds": [
            "The production stoppage was due to either a machinery fault or a supply shortage.",
            "Technicians ran diagnostics on all machinery and confirmed all units are operating correctly.",
            "A supply shortage requires the procurement team to issue an emergency order.",
            "An emergency procurement order triggers a budget review.",
        ],
        "goal": "A budget review has been triggered.",
        "steps": [
            {
                "text": "The production stoppage was not due to a machinery fault.",
                "support": ["Technicians ran diagnostics on all machinery and confirmed all units are operating correctly."],
            },
            {
                "text": "The production stoppage was due to a supply shortage.",
                "support": [
                    "The production stoppage was due to either a machinery fault or a supply shortage.",
                    "The production stoppage was not due to a machinery fault.",
                ],
            },
            {
                "text": "The procurement team must issue an emergency order.",
                "support": [
                    "The production stoppage was due to a supply shortage.",
                    "A supply shortage requires the procurement team to issue an emergency order.",
                ],
            },
            {
                "text": "A budget review has been triggered.",
                "support": [
                    "The procurement team must issue an emergency order.",
                    "An emergency procurement order triggers a budget review.",
                ],
            },
        ],
    },

    # ── HYPOTHETICAL SYLLOGISM WITH FULL INSTANTIATION ──────────────────────
    # These explicitly show every intermediate instantiated fact (not just the rules)

    {
        "id": "hs_ann_01", "pattern": "hypothetical_syllogism_annotated",
        "seeds": [
            "If the containment unit fails, the specimen escapes.",
            "If the specimen escapes, the facility enters lockdown.",
            "If the facility enters lockdown, all external communications are cut.",
            "The containment unit has failed.",
        ],
        "goal": "All external communications have been cut.",
        "steps": [
            {
                "text": "The specimen has escaped.",
                "support": [
                    "If the containment unit fails, the specimen escapes.",
                    "The containment unit has failed.",
                ],
            },
            {
                "text": "The facility has entered lockdown.",
                "support": [
                    "If the specimen escapes, the facility enters lockdown.",
                    "The specimen has escaped.",
                ],
            },
            {
                "text": "All external communications have been cut.",
                "support": [
                    "If the facility enters lockdown, all external communications are cut.",
                    "The facility has entered lockdown.",
                ],
            },
        ],
    },
    {
        "id": "hs_ann_02", "pattern": "hypothetical_syllogism_annotated",
        "seeds": [
            "If the reactor temperature exceeds safe limits, the coolant pump activates.",
            "If the coolant pump activates, water pressure in the primary loop increases.",
            "If water pressure in the primary loop increases, the pressure relief valve opens.",
            "The reactor temperature has exceeded safe limits.",
        ],
        "goal": "The pressure relief valve has opened.",
        "steps": [
            {
                "text": "The coolant pump has activated.",
                "support": [
                    "If the reactor temperature exceeds safe limits, the coolant pump activates.",
                    "The reactor temperature has exceeded safe limits.",
                ],
            },
            {
                "text": "Water pressure in the primary loop has increased.",
                "support": [
                    "If the coolant pump activates, water pressure in the primary loop increases.",
                    "The coolant pump has activated.",
                ],
            },
            {
                "text": "The pressure relief valve has opened.",
                "support": [
                    "If water pressure in the primary loop increases, the pressure relief valve opens.",
                    "Water pressure in the primary loop has increased.",
                ],
            },
        ],
    },
]


# ---------------------------------------------------------------------------
# Masking procedure: chain → training examples
# ---------------------------------------------------------------------------

def _step_text(step) -> str:
    return step["text"] if isinstance(step, dict) else step


def _step_support(step) -> list[str] | None:
    """Return explicit support premises if annotated, else None."""
    if isinstance(step, dict):
        return step.get("support")
    return None


def build_chains() -> list[dict]:
    """
    Convert all chains into training examples.

    Unannotated steps (plain strings): full-context masking —
      premises = seeds + all prior steps
    Annotated steps (dicts with 'support'): oracle masking —
      premises = support premises only (tightest possible signal)
    Oracle examples are generated twice to upweight targeted patterns.
    """
    from dras.preprocess import _format
    from dras.synth_extended import EXT_CHAINS
    examples = []

    for chain in CHAINS:
        seeds = chain["seeds"]
        goal = chain["goal"]
        accumulated = list(seeds)
        for step in chain["steps"]:
            text = _step_text(step)
            examples.append({"text": _format(goal, accumulated, text)})
            accumulated.append(text)

    for chain in ANNOTATED_CHAINS:
        seeds = chain["seeds"]
        goal = chain["goal"]
        accumulated = list(seeds)
        for step in chain["steps"]:
            text = _step_text(step)
            support = _step_support(step)
            if support:
                # oracle example — model sees only the 2-3 directly supporting premises
                oracle = _format(goal, support, text)
                examples.append({"text": oracle})
                examples.append({"text": oracle})   # upweight x2: these are the key patterns
            full_ctx = _format(goal, accumulated, text)
            repeat = 1
            for _ in range(repeat):
                examples.append({"text": full_ctx})
            accumulated.append(text)

    # extended full-context chains (~20 per pattern, diverse domains)
    for chain in EXT_CHAINS:
        seeds = chain["seeds"]
        goal = chain["goal"]
        accumulated = list(seeds)
        for step in chain["steps"]:
            text = _step_text(step)
            examples.append({"text": _format(goal, accumulated, text)})
            accumulated.append(text)

    return examples


def build_retriever_pairs() -> list[tuple[str, str]]:
    """
    Returns (query, positive_premise) pairs for contrastive retriever training.

    The retriever needs to learn: for a given goal, ALL premises in that chain
    are potentially relevant — not just the most goal-similar ones.

    For annotated chains we also emit (goal, support_premise) pairs with higher
    specificity: these teach the retriever to surface exactly the premises needed
    for each derivation step.
    """
    from dras.synth_extended import EXT_CHAINS
    pairs: list[tuple[str, str]] = []

    # Unannotated: every seed and derived step is a positive for the goal
    for chain in CHAINS:
        goal = chain["goal"]
        for premise in chain["seeds"]:
            pairs.append((goal, premise))
        for step in chain["steps"]:
            pairs.append((goal, _step_text(step)))

    # Annotated: support premises are high-quality positives
    for chain in ANNOTATED_CHAINS:
        goal = chain["goal"]
        for premise in chain["seeds"]:
            pairs.append((goal, premise))
        for step in chain["steps"]:
            pairs.append((goal, _step_text(step)))
            support = _step_support(step)
            if support:
                for sp in support:
                    # emit twice: support premises are the most valuable training signal
                    pairs.append((goal, sp))
                    pairs.append((goal, sp))

    # Extended chains — entry-point seeds get extra pairs so retriever learns
    # to surface them even when they are semantically distant from the goal.
    for chain in EXT_CHAINS:
        goal = chain["goal"]
        seeds = chain["seeds"]
        for premise in seeds:
            pairs.append((goal, premise))
        for step in chain["steps"]:
            pairs.append((goal, _step_text(step)))
        # Upweight the first seed (entity/entry-point fact) to fix retrieval
        # of goal-distant premises in long chains
        if seeds:
            pairs.append((goal, seeds[-1]))  # entity fact is typically last

    return pairs
